syntax = "proto3";

package product;

option go_package = "github.com/Prakash-Ravichandran/go-ecommerce-api/proto/product";

import "google/protobuf/timestamp.proto";

service ProductService {
    rpc GetProducts (GetProductsRequest) returns (GetProductsResponse);
    rpc ListProductsByID (ListProductsByIDRequest) returns (ListProductsByIDResponse);
    rpc CreateProducts (CreateProductsRequest) returns (CreateProductsResponse);
    rpc UpdateProducts (UpdateProductsRequest) returns (UpdateProductsResponse);
}

message GetProductsRequest {}

message Product {
   int64 id = 1;
   string name = 2;
   int32 price_in_cents = 3;
   int32 quantity = 4;
   google.protobuf.Timestamp created_at = 5;
}

message GetProductsResponse {
    repeated Product products = 1;
}

message ListProductsByIDRequest {
      int64 id = 1;
}

message  ListProductsByIDResponse {
    Product product = 1;
}

message CreateProductsRequest {
   int64 id = 1;
   string name = 2;
   int32 price_in_cents = 3;
   int32 quantity = 4;
   google.protobuf.Timestamp created_at = 5;
}

message CreateProductsResponse {
    Product product = 1;
}

message UpdateProductsRequest {
   int64 id = 1;
   optional string name = 2;
   optional int32 price_in_cents = 3;
   optional int32 quantity = 4;
   optional google.protobuf.Timestamp created_at = 5;
}

message UpdateProductsResponse {
    Product product = 1;
}
